=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

OpenAPI spec version: 0.25.1
Contact: contact@skycoin.net
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SkyApi::Apiv1wallettransactionHoursSelection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Apiv1wallettransactionHoursSelection' do
  before do
    # run before each test
    @instance = SkyApi::Apiv1wallettransactionHoursSelection.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Apiv1wallettransactionHoursSelection' do
    it 'should create an instance of Apiv1wallettransactionHoursSelection' do
      expect(@instance).to be_instance_of(SkyApi::Apiv1wallettransactionHoursSelection)
    end
  end
  describe 'test attribute "mode"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "share_factor"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
