=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

OpenAPI spec version: 0.25.1
Contact: skycoin.doe@example.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/apiv1exploreraddress_inputs'
require 'swagger_client/models/apiv1exploreraddress_status'
require 'swagger_client/models/apiv1pending_txs_transaction'
require 'swagger_client/models/apiv1wallets_meta'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_10'
require 'swagger_client/models/inline_response_200_10_unconfirmed_verify_transaction'
require 'swagger_client/models/inline_response_200_11'
require 'swagger_client/models/inline_response_200_11_head'
require 'swagger_client/models/inline_response_200_11_head_outputs'
require 'swagger_client/models/inline_response_200_12'
require 'swagger_client/models/inline_response_200_13'
require 'swagger_client/models/inline_response_200_13_richlist'
require 'swagger_client/models/inline_response_200_14'
require 'swagger_client/models/inline_response_200_14_status'
require 'swagger_client/models/inline_response_200_14_txn'
require 'swagger_client/models/inline_response_200_15'
require 'swagger_client/models/inline_response_200_15_entries'
require 'swagger_client/models/inline_response_200_15_meta'
require 'swagger_client/models/inline_response_200_16'
require 'swagger_client/models/inline_response_200_17'
require 'swagger_client/models/inline_response_200_18'
require 'swagger_client/models/inline_response_200_18_balance'
require 'swagger_client/models/inline_response_200_18_txn'
require 'swagger_client/models/inline_response_200_19'
require 'swagger_client/models/inline_response_200_19_transaction'
require 'swagger_client/models/inline_response_200_19_transactions'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_20'
require 'swagger_client/models/inline_response_200_21'
require 'swagger_client/models/inline_response_200_22'
require 'swagger_client/models/inline_response_200_22_data'
require 'swagger_client/models/inline_response_200_23'
require 'swagger_client/models/inline_response_200_23_data'
require 'swagger_client/models/inline_response_200_23_data_transaction'
require 'swagger_client/models/inline_response_200_23_error'
require 'swagger_client/models/inline_response_200_24'
require 'swagger_client/models/inline_response_200_25'
require 'swagger_client/models/inline_response_200_26'
require 'swagger_client/models/inline_response_200_2_addresses'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_3_body'
require 'swagger_client/models/inline_response_200_3_body_inputs'
require 'swagger_client/models/inline_response_200_3_body_outputs'
require 'swagger_client/models/inline_response_200_3_body_txns'
require 'swagger_client/models/inline_response_200_3_header'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_4_head'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_5_peers'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_6_blocks'
require 'swagger_client/models/inline_response_200_6_header'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/inline_response_200_9_blockchain'
require 'swagger_client/models/inline_response_200_9_unconfirmed_verify_transaction'
require 'swagger_client/models/inline_response_200_9_version'
require 'swagger_client/models/inline_response_default'

# APIs
require 'swagger_client/api/default_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
