=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

OpenAPI spec version: 0.25.1
Contact: skycoin.doe@example.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

# Common files
require 'sky_api/api_client'
require 'sky_api/api_error'
require 'sky_api/version'
require 'sky_api/configuration'

# Models
require 'sky_api/models/apiv1exploreraddress_inputs'
require 'sky_api/models/apiv1exploreraddress_outputs'
require 'sky_api/models/apiv1exploreraddress_status'
require 'sky_api/models/apiv1pending_txs_transaction'
require 'sky_api/models/apiv1wallets_entries'
require 'sky_api/models/apiv1wallets_meta'
require 'sky_api/models/apiv1wallettransaction_hours_selection'
require 'sky_api/models/apiv1wallettransaction_to'
require 'sky_api/models/apiv1wallettransaction_wallet'
require 'sky_api/models/inline_object'
require 'sky_api/models/inline_response200'
require 'sky_api/models/inline_response2001'
require 'sky_api/models/inline_response2002'
require 'sky_api/models/inline_response2003'
require 'sky_api/models/inline_response2003_unconfirmed_verify_transaction'
require 'sky_api/models/inline_response2004'
require 'sky_api/models/inline_response2005'
require 'sky_api/models/inline_response2006'
require 'sky_api/models/inline_response2007'
require 'sky_api/models/inline_response2007_data'
require 'sky_api/models/inline_response_default'

# APIs
require 'sky_api/api/default_api'

module SkyApi
  class << self
    # Customize default settings for the SDK using block.
    #   SkyApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
