=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

OpenAPI spec version: 0.25.1
Contact: skycoin.doe@example.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

module SkyApi
  VERSION = '0.25.1'
end
